spring:
  http:
    encoding.charset: UTF-8
    encoding.force: true
  aop:
    proxy-target-class: true
  jackson:
    generator:
      WRITE_NUMBERS_AS_STRINGS: true

server:
  port: 8080
  undertow:
    io-threads: 2
    worker-threads: 200

cors:
  mappings: /**
  allowedOrigins:

